In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from tensorflow import keras

In [ ]:
df = pd.read_csv('/content/iris.csv')

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.isnull()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['species']=le.fit_transform(df['species'])
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
species_name = le.classes_
print(species_name)

['setosa' 'versicolor' 'virginica']


In [ ]:
x = df.drop(columns=['species'])
y=df['species']
x.head(3)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [ ]:
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.3, shuffle=True, random_state=69)

In [ ]:
x_train.shape

(105, 4)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train[:1])

[[-1.14630942 -1.44374444 -0.25650655 -0.258263  ]]


In [ ]:
y_train = keras.utils.to_categorical(y_train, num_classes = 3)
print(y_train[:5])

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu',input_shape=(x_train.shape[-1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=3,activation='softmax'))

In [ ]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 32)                160       
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1315 (5.14 KB)
Trainable params: 1315 (5.14 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train, epochs=100, verbose = 2)


Epoch 1/100
4/4 - 1s - loss: 1.0922 - accuracy: 0.3714 - 892ms/epoch - 223ms/step
Epoch 2/100
4/4 - 0s - loss: 1.0188 - accuracy: 0.4286 - 18ms/epoch - 5ms/step
Epoch 3/100
4/4 - 0s - loss: 1.0182 - accuracy: 0.4476 - 13ms/epoch - 3ms/step
Epoch 4/100
4/4 - 0s - loss: 0.9314 - accuracy: 0.5619 - 14ms/epoch - 4ms/step
Epoch 5/100
4/4 - 0s - loss: 0.8421 - accuracy: 0.6571 - 15ms/epoch - 4ms/step
Epoch 6/100
4/4 - 0s - loss: 0.8790 - accuracy: 0.6190 - 19ms/epoch - 5ms/step
Epoch 7/100
4/4 - 0s - loss: 0.8058 - accuracy: 0.6952 - 21ms/epoch - 5ms/step
Epoch 8/100
4/4 - 0s - loss: 0.7730 - accuracy: 0.7429 - 17ms/epoch - 4ms/step
Epoch 9/100
4/4 - 0s - loss: 0.7534 - accuracy: 0.7619 - 15ms/epoch - 4ms/step
Epoch 10/100
4/4 - 0s - loss: 0.6786 - accuracy: 0.8095 - 17ms/epoch - 4ms/step
Epoch 11/100
4/4 - 0s - loss: 0.6724 - accuracy: 0.8095 - 16ms/epoch - 4ms/step
Epoch 12/100
4/4 - 0s - loss: 0.6775 - accuracy: 0.7524 - 15ms/epoch - 4ms/step
Epoch 13/100
4/4 - 0s - loss: 0.6552 - accurac

In [ ]:
prediction = model.predict(x_test)
print(prediction[:5])

2/2 [==============================] - 1s 10ms/step
[[9.9981403e-01 1.6225518e-04 2.3666655e-05]
 [7.8480039e-03 9.3229002e-01 5.9861936e-02]
 [9.9943674e-01 4.9722334e-04 6.6140929e-05]
 [2.8736473e-05 1.0062685e-02 9.8990858e-01]
 [9.9927282e-01 6.3838070e-04 8.8734028e-05]]


In [ ]:
prediction = np.argmax(prediction[])